# to run define K3S_TOKEN, K3S_VERSION is optional, eg:

version: "3.7"
services:
  master1:
    container_name: master1
    build: .
    entrypoint: /usr/local/bin/k3s
    command: server --cluster-init
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_TOKEN=230792876520407
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
      - 6443:6443
    networks:
      k3s-net:
        ipv4_address: 192.168.168.101

  master2:
    container_name: master2
    build: .
    entrypoint: /usr/local/bin/k3s
    command: server --server https://192.168.168.100:6443
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_TOKEN=230792876520407
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
      - NODE_IP=192.168.168.102
    depends_on:
      - master1
    networks:
      k3s-net:
        ipv4_address: 192.168.168.102

  master3:
    container_name: master3
    build: .
    entrypoint: /usr/local/bin/k3s
    command: server --server https://192.168.168.100:6443
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_TOKEN=230792876520407
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
      - NODE_IP=192.168.168.103
    depends_on:
      - master1
    networks:
      k3s-net:
        ipv4_address: 192.168.168.103

  agent:
    container_name: agent
    build:
      context: .
      dockerfile: Dockerfile-agent
    entrypoint: /usr/local/bin/k3s
    command: agent
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_URL=https://192.168.168.100:6443
      - K3S_TOKEN=230792876520407
    depends_on:
      - master3
    networks:
      k3s-net:
        ipv4_address: 192.168.168.114

networks:
  k3s-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.168.0/24
